security:
  encoders:
    App\Entity\User:
      algorithm: bcrypt

  providers:
    entity_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern: ^/api/test
      guard:
        authenticators:
          - App\Security\JwtAuthenticator
